// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5z28P2oIVTT0FvW2kVBi8CijecB25WzI',
    appId: '1:362925763810:web:724f0760547d35b84a02bb',
    messagingSenderId: '362925763810',
    projectId: 'syriancommunity-5239d',
    authDomain: 'syriancommunity-5239d.firebaseapp.com',
    storageBucket: 'syriancommunity-5239d.appspot.com',
    measurementId: 'G-318JMSTXST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSQtMlQwLsEkK5B1P4fjASVfZ0GCq1eLU',
    appId: '1:362925763810:android:d2a05fb59755d2e04a02bb',
    messagingSenderId: '362925763810',
    projectId: 'syriancommunity-5239d',
    storageBucket: 'syriancommunity-5239d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vIzUmGuN5XezNvhj-tbuGeK3ubnasXM',
    appId: '1:362925763810:ios:acdec5a216b241424a02bb',
    messagingSenderId: '362925763810',
    projectId: 'syriancommunity-5239d',
    storageBucket: 'syriancommunity-5239d.appspot.com',
    iosBundleId: 'com.example.syrianadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vIzUmGuN5XezNvhj-tbuGeK3ubnasXM',
    appId: '1:362925763810:ios:2ed67893c7f7730d4a02bb',
    messagingSenderId: '362925763810',
    projectId: 'syriancommunity-5239d',
    storageBucket: 'syriancommunity-5239d.appspot.com',
    iosBundleId: 'com.example.syrianadmin.RunnerTests',
  );
}
